# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3cfae097de1cd24c13eafe7ea652050008fb1ccbf88cf33450af345b4193bb95e8c68334ad7b2111cf9a0a6e7857fe4a83cfbd3360b9b3b5e4144dc03f4f72b

test:
  secret_key_base: 33a2671bfec382410a844b50d5ea1ebbb50caa143b60dba9fb0dd2ee28e3c0c960b8a263e5a006b9401ebc77894c41add7ce8839341eef4e2d94a28a3603f4ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
